"""empty message

Revision ID: 487f5f0aa948
Revises: daeaf3d1645d
Create Date: 2023-02-18 11:56:23.783864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487f5f0aa948'
down_revision = 'daeaf3d1645d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('habitantes', sa.Integer(), nullable=False),
    sa.Column('periodo_orbital', sa.Integer(), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    # ### end Alembic commands ###
