"""empty message

Revision ID: 60b202ac7f81
Revises: 9d8fb244ae12
Create Date: 2023-02-18 12:07:43.607327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b202ac7f81'
down_revision = '9d8fb244ae12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('cantidad_ruedas', sa.Integer(), nullable=False),
    sa.Column('consumo_combustible', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
